/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.saltsoft;

import com.google.gson.Gson;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws Exception {
//        System.out.println(new App().getGreeting());
//        NewReader newReader = new NewReader();
//        newReader.readLinesFromFile("U:\\dev\\projekt_3\\Go-bie\\src\\main\\java\\pl\\saltsoft\\App.java");
//
//
//        NewWriter newWriter = new NewWriter();
//        newWriter.writeFile("readMeMd");
//        Serializator zwhisky = new Serializator();
//        zwhisky.swhisky(new Whisky("IPA",11.8,15));
//
//        Whisky odczarojMojeWhyski = zwhisky.odczarojMojeWhyski("{\"name\":\"Johny\",\"alcohol\":11.8,\"ibu\":15}");
//System.out.println(odczarojMojeWhyski);
StartWorker mlekoJestZajebiaszcze = new StartWorker();
mlekoJestZajebiaszcze.startManyWorkers(10);
        }





    }


